spring:
  application:
    name: micro-airport-core
  config:
    import: optional:.env[.properties]

# Configuration data sources
  datasource:
    driver-class-name: org.postgresql.Driver
    url:
    username:
    password:

  #Liquibase
  liquibase:
    enabled: true
    change-log: classpath:db.changelog/db.changelog-master.yaml
    default-schema:

  #Email
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# MyBatis
mybatis:
  mapper-locations: classpath:mybatis.mapper/*.xml
  type-aliases-package: by.piskunou.solvdlaba.domain

jwt-secret:

server:
  port: 0

eureka:
  client:
    service-host: ${MAIN_HOST}
    service-url:
      defaultZone: http://${eureka.client.service-host}:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.value}
